spring:
  application:
    name: discovery-server-service
  cloud:
    config:
      enabled: false
  config:
    import: optional:configserver:http://localhost:8888



server:
  port: 8082

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false  #Eureka cannot register itself as a client.
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
