spring:
  application:
    name: config-server-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jairnb/workshop/tree/main/source/java/app/workshop-services-configurations
          skipSslValidation: true
server:
  port: 8082