spring:
  application:
    name: config-server-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jairnb/workshop.git
          skipSslValidation: true
          search-paths: /source/java/app/workshop-services-configurations

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/

server:
  port: 8082