spring:
  application:
    name: api-gateway-service
  profiles:
    active: default
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      enabled: false
    gateway:
      routes:
        - id: company-service
          uri: lb://company-service
          predicates:
            - Path=/api/v1/company/**, /api/v2/company/**
management:
  endpoints:
    web:
      exposure:
        include: gateway, health
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
    gateway:
      enabled: true # default value
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        all: true
        http.server.requests: true
  tracing:
    sampling:
      probability: 1.0
  prometheus:
    metrics:
      export:
        step: 10s
  info:
    env:
        enabled: true
    java:
        enabled: true
    os:
        enabled: true


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/


logging:
  level:
    org:
      springframework:
        web: debug
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}] tenantId=%X{tenantId:-}"

server:
  port: 8081