spring:
  application:
    name: api-gateway-service
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/