spring:
  application:
    name: company-service
  cloud:
    config:
      enabled: true
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  datasource:
    username: root
    password: password
    url: ${DATABASE_URL_COMPANY_SERVICE:jdbc:postgresql://localhost:5432/company_service}
  flyway:
    enabled: true
#  mvc:
#    problemdetails:
#      enabled: true
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8082/eureka/}

logging:
  level:
    org:
      springframework:
        web: debug
  config: classpath:logback-spring.xml

server:
  port: 8085

management: #Enableling all actuator endpoints
  endpoints:
    web:
      exposure:
        include: "*"