spring:
  application:
    name: company-service
  cloud:
    config:
      enabled: false
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  datasource:
    username: root
    password: password
    url: jdbc:postgresql://localhost:5432/company_service

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8082/eureka/}

server:
  port: 8085