spring:
  application:
    name: company-service
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888

#https://github.com/jairnb/workshop/tree/main/source/java/app/workshop-services-configurations

######
######################################################################################################
######## Server Configurations
server:
  port: 8085

######## Spring Configurations
#spring:
#  application:
#    name: company-service
#  profiles:
#        active: default,dev
#  datasource:
#    username: root
#    password: password
#    url: jdbc:postgresql://localhost:5432/company_service
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
#    show-sql: false
#    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: never

###### Eureka Configurations
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8081/eureka/



####### Cloud Configurations
#cloud:
#  aws:
#    region:
#      static: us-east-1
#    stack:
#      auto: false
#    credentials:
#      accessKey: ${AWSAccessKeyId}
#      secretKey: ${AWSSecretKey}
#
#aws:
#  bucket: workshop-app-bucket