spring:
  application:
    name: product-service
  config:
    import: optional:configserver:http://localhost:8082
#spring:
#  application:
#    name: product-service
#  datasource:
#    username: root
#    password: password
#    url: jdbc:postgresql://localhost:5432/product_service
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
#    show-sql: false
#    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: always
#  messages:
#    basename: messages,config.i18n.messages
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8081/eureka/
#
#server:
#  port: 8086
#
#workshop:
#  services:
#    company-service:
#      name: company-service
#      port: 8085