######## Server Configurations
server:
  port: 8085

######## Spring Configurations
spring:
  application:
    name: company-service
  profiles:
    active: de,default
  datasource:
    username: root
    password: password
    url: jdbc:postgresql://localhost:5432/company_service
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

###### Eureka Configurations
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/


