spring:
  application:
    name: employee-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/

#eureka:
#  instance:
#    hostname: localhost
#  client:
#    registerWithEureka: false  #Eureka cannot register itself as a client.
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
