spring:
  application:
    name: api-gateway-service
  config:
    import: optional:configserver:http://localhost:8888
    gateway:
      routes:
        - id: company-service
          uri: lb://company-service
          predicates:
            - Path=/api/v1/company/**

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
