spring:
  application:
    name: api-gateway-service
  profiles:
    active: default
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      enabled: true
    gateway:
      routes:
        - id: COMPANYSERVICE
          uri: lb://company-service
          predicates:
            - Path=/companies/**
management:
  endpoint:
    gateway:
      enabled: true # default value
  endpoints:
    web:
      exposure:
        include: gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/

server:
  port: 8081