######## Server Configurations
server:
  port: 8085

######## Spring Configurations
spring:
  application:
    name: company-service
  profiles:
    active: default
  datasource:
    username: root
    password: password
    url:  ${DATABASE_URL_COMPANY_SERVICE:jdbc:postgresql://localhost:5432/company_service}

###### Eureka Configurations
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8082/eureka/}

####### Cloud Configurations
#cloud:
#  aws:
#    region:
#      static: us-east-1
#    stack:
#      auto: false
#    credentials:
#      accessKey: ${AWSAccessKeyId}
#      secretKey: ${AWSSecretKey}
