######## Server Configurations
server:
  port: 8085

######## Spring Configurations
spring:
  application:
    name: company-service
  profiles:
    active: default
  datasource:
    username: root
    password: password
    url: jdbc:postgresql://localhost:5432/company_service
  flyway:
    enabled: true

###### Eureka Configurations
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        all: true
        http.server.requests: true
  tracing:
    sampling:
      probability: 1.0
  prometheus:
    metrics:
      export:
        step: 10s
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
