######## Server Configurations
server:
  port: 8085

######## Spring Configurations
spring:
  application:
    name: employee-service

###### Eureka Configurations
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/


