spring:
  application:
    name: config-server-service
  profiles:
    active: default
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jairnb/workshop.git
          skipSslValidation: true
          search-paths: /source/java/workshop/workshop-services-configurations
          default-label: dev
      enabled: false


eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/

server:
  port: 8888

#logging:
#  level:
#    root: info
