server:
  port: 8888

spring:
  application:
    name: config-server-service
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/Documents/dev/workshop
          skipSslValidation: true
          search-paths: /source/java/workshop/workshop-services-configurations

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/

management:
  endpoint:
    features:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: debug
